In [3]:
# Numpy array is a grid of values, values are indexed via a set of nonnegative integers.  
# Numpy arrays can be initiated from nested Python list.
# Need to import numpy library
# rank is the number of dimensions in the array

import numpy as np

In [7]:
x = np.array ([10,20,30])

In [8]:
print(type(x))

<class 'numpy.ndarray'>


In [9]:
print(x.shape)  # size of the numpy array

(3,)


In [10]:
print(x[0], x[1])  # accessing array elements with indexis

10 20


In [11]:
x[0] = 40 # changing array element

In [12]:
print(x) 

[40 20 30]


In [13]:
y = np.array([[10,20,30], [40,50,60]])  # create an array of rank 2

In [14]:
print(y.shape)  # returns number of elements in the array

(2, 3)


In [16]:
print (y[0,0], y[0,1], y[1,2])

10 20 60


In [17]:
x = np.zeros((2,2)) #create an array of zeros
print(x)

[[0. 0.]
 [0. 0.]]


In [18]:
y = np.ones((1,2))  # create an array of ones
print(y)

[[1. 1.]]


In [19]:
z = np.full((2,2), 7) # Return a array filled with the value 7
print(z)

[[7 7]
 [7 7]]


In [20]:
a = np.eye(3) # create an identify matrix, 3X3
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
b = np.random.random((2,2)) # create an array of random values
print(b)

[[0.84913206 0.09799417]
 [0.98429874 0.7777092 ]]


In [22]:
myarray = np.array([10,20,30,40], ndmin=2) #ndmin =2, minimum dimensions is 2
print(myarray)

[[10 20 30 40]]


In [29]:
x,y,z = np.loadtxt('..\\Data\\data.txt', skiprows=1, unpack=True, delimiter=" ") #load dataset from text file,
                                                    # skip the first row,
                                                    # unpack = True retuns the columns as separate arrays
    

In [30]:
print(x)
print(y)
print(z)

[100. 200. 300. 400.]
[200. 300. 400. 500.]
[150. 250. 350. 450.]


In [19]:
array2 = np.genfromtxt('..\\Data\\data2.txt', skip_header=1,filling_values =-999) #missing value will be -999
print(array2)

# refer to the doc https://numpy.org/devdocs/user/basics.io.genfromtxt.html#filling-values


[[ 100.  200.]
 [ 200. -999.]
 [ 300.  400.]
 [ 400.  500.]]


In [31]:
array1 = np.arange(start=0.1, stop=7.4, step=2.5) # create an array with starting value, increment value (step), and stop before value 10 is reached
print(array1)

# save data in text file
np.savetxt('out_data.txt', array1, delimiter=',')


[0.1 2.6 5.1]


In [32]:
a = np.ones ((2,3))
print(a)

b = np.random.random((2,3))
print(b)

print(a+b)

print(a-b)

print(a*b)

print(a/b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0.92721637 0.98984676 0.10640835]
 [0.15451317 0.16357494 0.43016594]]
[[1.92721637 1.98984676 1.10640835]
 [1.15451317 1.16357494 1.43016594]]
[[0.07278363 0.01015324 0.89359165]
 [0.84548683 0.83642506 0.56983406]]
[[0.92721637 0.98984676 0.10640835]
 [0.15451317 0.16357494 0.43016594]]
[[1.07849692 1.01025738 9.39775829]
 [6.47194006 6.11340597 2.32468427]]


In [33]:
x = np.array ([[0,1,2], [3,4,5]])
print(x)
print(x[1])  # all elements of index 1 (row 1)
print(x[0][2])  # element at row 0, column 0
print(x[0:2,1]) # element at row 0 and 1 (2-1), column 1
print(np.transpose(x))  # transposing the array, which means switch around the array shape


[[0 1 2]
 [3 4 5]]
[3 4 5]
2
[1 4]
[[0 3]
 [1 4]
 [2 5]]
